0. Basic Imports

from pprint import pprint
import pandas as pd
import zrd_login
import datetime
import pdb



kite = zrd_login.kite
pdb.set_trace()


1.1
	nifty100LowVolatility30list : 	watchlist = ['ACC', 'ASIANPAINT', 'BAJAJ-AUTO', 'BOSCHLTD', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'COLPAL', 'DABUR', 'DRREDDY', 'HCLTECH', 'HDFCBANK', 'HEROMOTOCO', 'HINDUNILVR', 'HDFC', 'ITC', 'IOC', 'INFY', 'KOTAKBANK', 'LT', 'MARICO', 'NTPC', 'NESTLEIND', 'PIDILITIND', 'POWERGRID', 'RELIANCE', 'TCS', 'TECHM', 'ULTRACEMCO', 'WIPRO']
	nifty200Momentum30_list : 		watchlist = ['ASIANPAINT', 'AUROPHARMA', 'BALKRISIND', 'BERGEPAINT', 'BHARTIARTL', 'BIOCON', 'BRITANNIA', 'CADILAHC', 'CIPLA', 'COLPAL', 'DABUR', 'DIVISLAB', 'DRREDDY', 'ESCORTS', 'GMRINFRA', 'HINDUNILVR', 'IGL', 'NAUKRI', 'JUBLFOOD', 'LUPIN', 'MGL', 'MUTHOOTFIN', 'NESTLEIND', 'PIDILITIND', 'RELIANCE', 'SRF', 'SHREECEM', 'TATACONSUM', 'TORNTPHARM', 'TORNTPOWER']
	Nifty50 						Watchlist = ['ADANIPORTS','APOLLOHOSP','ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJAJFINSV','BAJFINANCE','BHARTIARTL','BPCL','BRITANNIA','CIPLA','COALINDIA','DIVISLAB','DRREDDY','EICHERMOT','GRASIM','HCLTECH','HDFC','HDFCBANK','HDFCLIFE','HEROMOTOCO','HINDALCO','HINDUNILVR','ICICIBANK','INDUSINDBK','INFY','ITC','JSWSTEEL','KOTAKBANK','LT','M&M','MARUTI','NESTLEIND','NTPC','ONGC','POWERGRID','RELIANCE','SBILIFE','SBIN','SHREECEM','SUNPHARMA','TATACONSUM','TATAMOTORS','TATASTEEL','TCS','TECHM','TITAN','ULTRACEMCO','UPL','WIPRO']
	niftymidcap50list : 			watchlist = ['ADANIENT', 'AMARAJABAT', 'APOLLOHOSP', 'APOLLOTYRE', 'ASHOKLEY', 'BALKRISIND', 'BANKINDIA', 'BATAINDIA', 'BEL', 'BHARATFORG', 'BHEL', 'CANBK', 'CASTROLIND', 'CHOLAFIN', 'COFORGE', 'CUMMINSIND', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'GMRINFRA', 'GLENMARK', 'GODREJPROP', 'IDFCFIRSTB', 'IBULHSGFIN', 'JINDALSTEL', 'JUBLFOOD', 'L&TFH', 'LICHSGFIN', 'MRF', 'MGL', 'M&MFIN', 'MANAPPURAM', 'MFSL', 'MINDTREE', 'NATIONALUM', 'PAGEIND', 'RBLBANK', 'RECLTD', 'SRF', 'SRTRANSFIN', 'SAIL', 'SUNTV', 'TVSMOTOR', 'TATAPOWER', 'RAMCOCEM', 'TORNTPOWER', 'UNIONBANK', 'IDEA', 'VOLTAS', 'ZEEL']
	niftysmallcap50list : 			watchlist = ['AVANTIFEED', 'BAJAJELEC', 'BDL', 'BIRLACORPN', 'CANFINHOME', 'CEATLTD', 'CENTURYTEX', 'CHAMBLFERT', 'COCHINSHIP', 'CYIENT', 'DCBBANK', 'DCMSHRIRAM', 'DEEPAKNTR', 'DBL', 'DIXON', 'GMMPFAUDLR', 'GODFRYPHLP', 'GRANULES', 'GRAPHITE', 'IDFC', 'IRCON', 'INDIAMART', 'INDIANB', 'KAJARIACER', 'KEC', 'LAURUSLABS', 'LINDEINDIA', 'MOIL', 'MIDHANI', 'MCX', 'NBCC', 'PNBHOUSING', 'PVR', 'PERSISTENT', 'PGHL', 'RITES', 'RADICO', 'RVNL', 'RALLIS', 'SPICEJET', 'STLTECH', 'STAR', 'SPARC', 'SUNTECK', 'TV18BRDCST', 'TATAELXSI', 'UJJIVANSFB', 'VIPIND', 'VAKRANGEE', 'WOCKPHARMA']
	nifty_Alpha_Index : 			watchlist = ['ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ATGL', 'AJANTPHARM', 'APLLTD', 'AMBER', 'ASTRAZEN', 'DMART', 'BALKRISIND', 'BAYERCROP', 'BERGEPAINT', 'BSOFT', 'CDSL', 'COFORGE', 'COROMANDEL', 'DEEPAKNTR', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'ESCORTS', 'GMMPFAUDLR', 'GRANULES', 'GUJGASLTD', 'HCLTECH', 'ISEC', 'INDIAMART', 'NAUKRI', 'IPCALAB', 'JBCHEPHARM', 'JINDALSTEL', 'JUBLFOOD', 'LAURUSLABS', 'METROPOLIS', 'MCX', 'MUTHOOTFIN', 'NAVINFLUOR', 'NESTLEIND', 'PIIND', 'RALLIS', 'RELAXO', 'RELIANCE', 'SRF', 'TATACONSUM', 'TORNTPHARM', 'TRENT', 'VBL', 'IDEA']
	nifty_alpha_lowvol30list : 		watchlist = ['AMBUJACEM', 'ASIANPAINT', 'BERGEPAINT', 'BIOCON', 'BRITANNIA', 'CADILAHC', 'CIPLA', 'COLPAL', 'DABUR', 'DIVISLAB', 'DRREDDY', 'HCLTECH', 'HAVELLS', 'HINDUNILVR', 'IGL', 'INFY', 'LUPIN', 'MRF', 'MARICO', 'NESTLEIND', 'PIDILITIND', 'POWERGRID', 'RELIANCE', 'SRF', 'SHREECEM', 'TCS', 'TORNTPHARM', 'TORNTPOWER', 'VOLTAS', 'WIPRO']
	nifty_High_Beta50_Index : 		watchlist = ['ADANIPORTS', 'APOLLOTYRE', 'ASHOKLEY', 'AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'BANDHANBNK', 'BANKBARODA', 'BHEL', 'BPCL', 'CANFINHOME', 'CANBK', 'CHOLAFIN', 'COFORGE', 'DLF', 'ESCORTS', 'FEDERALBNK', 'GODREJPROP', 'GRASIM', 'HINDALCO', 'HDFC', 'ICICIBANK', 'ICICIPRULI', 'IDFCFIRSTB', 'IBULHSGFIN', 'INDUSINDBK', 'JSWSTEEL', 'JINDALSTEL', 'L&TFH', 'LICHSGFIN', 'M&MFIN', 'MANAPPURAM', 'MARUTI', 'MFSL', 'MOTHERSUMI', 'MUTHOOTFIN', 'NMDC', 'NAM-INDIA', 'PEL', 'PFC', 'RBLBANK', 'RADICO', 'SRTRANSFIN', 'SBIN', 'SAIL', 'TATAMOTORS', 'TATASTEEL', 'UJJIVAN', 'VEDL', 'IDEA']
	fno								watchlist = ['BPCL', 'MOTHERSUMI', 'RBLBANK', 'SIEMENS', 'GODREJPROP', 'CANBK', 'MARICO', 'BEL', 'NAVINFLUOR', 'CADILAHC', 'SRF', 'DEEPAKNTR', 'UBL', 'NAUKRI', 'LUPIN', 'PVR', 'COLPAL', 'PNB', 'IOC', 'BHEL', 'PETRONET', 'IDFCFIRSTB', 'GRANULES', 'EICHERMOT', 'M&MFIN', 'VOLTAS', 'IGL', 'HINDPETRO', 'TVSMOTOR', 'TATACHEM', 'BANDHANBNK', 'HAVELLS', 'SUNTV', 'AUBANK', 'L&TFH', 'ADANIENT', 'M&M', 'LTI', 'HDFC', 'MINDTREE', 'INFY', 'RAMCOCEM', 'TATAMOTORS', 'SUNPHARMA', 'TITAN', 'SBILIFE', 'POWERGRID', 'VEDL', 'AARTIIND', 'NTPC', 'IBULHSGFIN', 'LICHSGFIN', 'UPL', 'RECLTD', 'BOSCHLTD', 'APLLTD', 'BRITANNIA', 'COFORGE', 'NAM-INDIA', 'JSWSTEEL', 'NMDC', 'GRASIM', 'HDFCAMC', 'HDFCLIFE', 'JINDALSTEL', 'PFC', 'SHREECEM', 'BANKBARODA', 'LTTS', 'AMARAJABAT', 'HCLTECH', 'APOLLOTYRE', 'MCDOWELL-N', 'BALKRISIND', 'ICICIGI', 'ALKEM', 'CUB', 'IRCTC', 'MPHASIS', 'ULTRACEMCO', 'AXISBANK', 'ASIANPAINT', 'TORNTPOWER', 'BHARATFORG', 'HINDALCO', 'ESCORTS', 'TATACONSUM', 'ZEEL', 'ASHOKLEY', 'DLF', 'GUJGASLTD', 'ICICIPRULI', 'LT', 'TORNTPHARM', 'CHOLAFIN', 'JUBLFOOD', 'ITC', 'INDUSTOWER', 'SRTRANSFIN', 'GMRINFRA', 'HEROMOTOCO', 'LALPATHLAB', 'EXIDEIND', 'BAJFINANCE', 'DABUR', 'GODREJCP', 'NATIONALUM', 'PEL', 'BIOCON', 'TCS', 'GAIL', 'GLENMARK', 'ACC', 'APOLLOHOSP', 'CIPLA', 'BAJAJ-AUTO', 'PIIND', 'BHARTIARTL', 'NESTLEIND', 'INDIGO', 'MRF', 'SBIN', 'COALINDIA', 'AUROPHARMA', 'DIVISLAB', 'BAJAJFINSV', 'RELIANCE', 'IDEA', 'TATAPOWER', 'WIPRO', 'ADANIPORTS', 'BERGEPAINT', 'TATASTEEL', 'FEDERALBNK', 'MFSL', 'KOTAKBANK', 'MGL', 'HINDUNILVR', 'TECHM', 'DRREDDY', 'SAIL', 'MARUTI', 'ICICIBANK', 'BATAINDIA', 'MUTHOOTFIN', 'HDFCBANK', 'ONGC', 'INDUSINDBK', 'PIDILITIND', 'AMBUJACEM', 'PAGEIND', 'TRENT', 'CONCOR', 'PFIZER', 'MANAPPURAM', 'CUMMINSIND']
	nifty 500                            	watchlist = ['3MINDIA', 'ABB', 'POWERINDIA', 'ACC', 'AIAENG', 'APLAPOLLO', 'AUBANK', 'AARTIDRUGS', 'AARTIIND', 'AAVAS', 'ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ATGL', 'ADANITRANS', 'ABCAPITAL', 'ABFRL', 'ADVENZYMES', 'AEGISCHEM', 'AFFLE', 'AJANTPHARM', 'AKZOINDIA', 'ALEMBICLTD', 'APLLTD', 'ALKEM', 'ALKYLAMINE', 'ALOKINDS', 'AMARAJABAT', 'AMBER', 'AMBUJACEM', 'ANGELBRKG', 'APOLLOHOSP', 'APOLLOTYRE', 'ASAHIINDIA', 'ASHOKLEY', 'ASHOKA', 'ASIANPAINT', 'ASTERDM', 'ASTRAZEN', 'ASTRAL', 'ATUL', 'AUROPHARMA', 'AVANTIFEED', 'DMART', 'AXISBANK', 'BASF', 'BEML', 'BSE', 'BAJAJ-AUTO', 'BAJAJCON', 'BAJAJELEC', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BALAMINES', 'BALKRISIND', 'BALMLAWRIE', 'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'MAHABANK', 'BATAINDIA', 'BAYERCROP', 'BERGEPAINT', 'BDL', 'BEL', 'BHARATFORG', 'BHEL', 'BPCL', 'BHARATRAS', 'BHARTIARTL', 'BIOCON', 'BIRLACORPN', 'BSOFT', 'BLISSGVS', 'BLUEDART', 'BLUESTARCO', 'BBTC', 'BOSCHLTD', 'BRIGADE', 'BRITANNIA', 'BURGERKING', 'CCL', 'CESC', 'CRISIL', 'CSBBANK', 'CADILAHC', 'CANFINHOME', 'CANBK', 'CAPLIPOINT', 'CGCL', 'CARBORUNIV', 'CASTROLIND', 'CEATLTD', 'CENTRALBK', 'CDSL', 'CENTURYPLY', 'CENTURYTEX', 'CERA', 'CHALET', 'CHAMBLFERT', 'CHOLAHLDNG', 'CHOLAFIN', 'CIPLA', 'CUB', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CAMS', 'CONCOR', 'COROMANDEL', 'CREDITACC', 'CROMPTON', 'CUMMINSIND', 'CYIENT', 'DCBBANK', 'DCMSHRIRAM', 'DLF', 'DABUR', 'DALBHARAT', 'DEEPAKNTR', 'DELTACORP', 'DHANI', 'DHANUKA', 'DBL', 'DISHTV', 'DCAL', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'EIHOTEL', 'EPL', 'EDELWEISS', 'EICHERMOT', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE', 'ENGINERSIN', 'EQUITAS', 'ERIS', 'ESCORTS', 'EXIDEIND', 'FDC', 'FEDERALBNK', 'FINEORG', 'FINCABLES', 'FINPIPE', 'FSL', 'FORTIS', 'FCONSUMER', 'FRETAIL', 'GAIL', 'GEPIL', 'GMMPFAUDLR', 'GMRINFRA', 'GALAXYSURF', 'GRSE', 'GARFIBRES', 'GICRE', 'GILLETTE', 'GLAXO', 'GLENMARK', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GESHIP', 'GREAVESCOT', 'GRINDWELL', 'GUJALKALI', 'GAEL', 'FLUOROCHEM', 'GUJGASLTD', 'GNFC', 'GPPL', 'GSFC', 'GSPL', 'GULFOILLUB', 'HEG', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HFCL', 'HAPPSTMNDS', 'HATSUN', 'HAVELLS', 'HEIDELBERG', 'HEMIPROP', 'HEROMOTOCO', 'HSCL', 'HINDALCO', 'HAL', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HONAUT', 'HUDCO', 'HDFC', 'HUHTAMAKI', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ISEC', 'IDBI', 'IDFCFIRSTB', 'IDFC', 'IFBIND', 'IIFL', 'IIFLWAM', 'IOLCP', 'IRB', 'IRCON', 'ITC', 'ITI', 'INDIACEM', 'IBULHSGFIN', 'IBREALEST', 'INDIAMART', 'INDIANB', 'IEX', 'INDHOTEL', 'IOC', 'IOB', 'IRCTC', 'ICIL', 'INDOCO', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'INFIBEAM', 'NAUKRI', 'INFY', 'INGERRAND', 'INOXLEISUR', 'INTELLECT', 'INDIGO', 'IPCALAB', 'JBCHEPHARM', 'JKCEMENT', 'JKLAKSHMI', 'JKPAPER', 'JKTYRE', 'JMFINANCIL', 'JSWENERGY', 'JSWSTEEL', 'JTEKTINDIA', 'JAMNAAUTO', 'JINDALSAW', 'JSLHISAR', 'JSL', 'JINDALSTEL', 'JCHAC', 'JUBLFOOD', 'JUSTDIAL', 'JYOTHYLAB', 'KPRMILL', 'KEI', 'KNRCON', 'KPITTECH', 'KRBL', 'KSB', 'KAJARIACER', 'KALPATPOWR', 'KANSAINER', 'KARURVYSYA', 'KSCL', 'KEC', 'KOTAKBANK', 'L&TFH', 'LTTS', 'LICHSGFIN', 'LAOPALA', 'LAXMIMACH', 'LTI', 'LT', 'LAURUSLABS', 'LEMONTREE', 'LINDEINDIA', 'LUPIN', 'LUXIND', 'MASFIN', 'MMTC', 'MOIL', 'MRF', 'MGL', 'MAHSCOOTER', 'MAHSEAMLES', 'M&MFIN', 'M&M', 'MAHINDCIE', 'MHRIL', 'MAHLOG', 'MANAPPURAM', 'MRPL', 'MARICO', 'MARUTI', 'MFSL', 'MAXHEALTH', 'MAZDOCK', 'METROPOLIS', 'MINDTREE', 'MINDACORP', 'MINDAIND', 'MIDHANI', 'MOTHERSUMI', 'MOTILALOFS', 'MPHASIS', 'MCX', 'MUTHOOTFIN', 'NATCOPHARM', 'NBCC', 'NCC', 'NESCO', 'NHPC', 'NLCINDIA', 'NMDC', 'NOCIL', 'NTPC', 'NH', 'NATIONALUM', 'NFL', 'NAVINFLUOR', 'NESTLEIND', 'NETWORK18', 'NILKAMAL', 'NAM-INDIA', 'OBEROIRLTY', 'ONGC', 'OIL', 'OFSS', 'ORIENTELEC', 'ORIENTREF', 'PIIND', 'PNBHOUSING', 'PNCINFRA', 'PVR', 'PAGEIND', 'PERSISTENT', 'PETRONET', 'PFIZER', 'PHILIPCARB', 'PHOENIXLTD', 'PIDILITIND', 'PEL', 'POLYMED', 'POLYCAB', 'POLYPLEX', 'PFC', 'POWERGRID', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PGHL', 'PGHH', 'PNB', 'QUESS', 'RBLBANK', 'RECLTD', 'RITES', 'RADICO', 'RVNL', 'RAIN', 'RAJESHEXPO', 'RALLIS', 'RCF', 'RATNAMANI', 'RAYMOND', 'REDINGTON', 'RELAXO', 'RELIANCE', 'RESPONIND', 'ROSSARI', 'ROUTE', 'SBICARD', 'SBILIFE', 'SIS', 'SJVN', 'SKFINDIA', 'SRF', 'SANOFI', 'SCHAEFFLER', 'SCHNEIDER', 'SEQUENT', 'SHARDACROP', 'SFL', 'SHILPAMED', 'SCI', 'SHOPERSTOP', 'SHREECEM', 'SHRIRAMCIT', 'SRTRANSFIN', 'SIEMENS', 'SOBHA', 'SOLARINDS', 'SOLARA', 'SONATSOFTW', 'SPANDANA', 'SPICEJET', 'STARCEMENT', 'SBIN', 'SAIL', 'SWSOLAR', 'STLTECH', 'STAR', 'SUDARSCHEM', 'SUMICHEM', 'SPARC', 'SUNPHARMA', 'SUNTV', 'SUNCLAYLTD', 'SUNDARMFIN', 'SUNDRMFAST', 'SUNTECK', 'SUPRAJIT', 'SUPREMEIND', 'SUPPETRO', 'SUVENPHAR', 'SUZLON', 'SWANENERGY', 'SYMPHONY', 'SYNGENE', 'TCIEXP', 'TCNSBRANDS', 'TTKPRESTIG', 'TV18BRDCST', 'TVSMOTOR', 'TANLA', 'TASTYBITE', 'TATACHEM', 'TATACOFFEE', 'TATACOMM', 'TCS', 'TATACONSUM', 'TATAELXSI', 'TATAINVEST', 'TATAMTRDVR', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TEAMLEASE', 'TECHM', 'NIACL', 'RAMCOCEM', 'THERMAX', 'THYROCARE', 'TIMKEN', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TRIDENT', 'TRITURBINE', 'TIINDIA', 'UCOBANK', 'UFLEX', 'UPL', 'UTIAMC', 'UJJIVAN', 'UJJIVANSFB', 'ULTRACEMCO', 'UNIONBANK', 'UBL', 'MCDOWELL-N', 'VGUARD', 'VMART', 'VIPIND', 'VSTIND', 'VAIBHAVGBL', 'VAKRANGEE', 'VALIANTORG', 'VTL', 'VARROC', 'VBL', 'VEDL', 'VENKEYS', 'VINATIORGA', 'IDEA', 'VOLTAS', 'WABCOINDIA', 'WELCORP', 'WELSPUNIND', 'WESTLIFE', 'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA', 'YESBANK', 'ZEEL', 'ZENSARTECH', 'ZYDUSWELL', 'ECLERX']



1.2   NIFTY50_List = ['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BPCL', 'BHARTIARTL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'HDFC', 'ICICIBANK', 'ITC', 'IOC', 'INDUSINDBK', 'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC', 'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SHREECEM', 'SBIN', 'SUNPHARMA', 'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'UPL', 'ULTRACEMCO', 'WIPRO']
	 NIFTY 500 = ['3MINDIA','ABB','POWERINDIA','ACC','AIAENG','APLAPOLLO','AUBANK','AARTIDRUGS','AARTIIND','AAVAS','ABBOTINDIA','ADANIENT','ADANIGREEN','ADANIPORTS','ATGL','ADANITRANS','ABCAPITAL','ABFRL','ADVENZYMES','AEGISCHEM','AFFLE','AJANTPHARM','AKZOINDIA','ALEMBICLTD','APLLTD','ALKEM','ALKYLAMINE','ALOKINDS','AMARAJABAT','AMBER','AMBUJACEM','ANGELBRKG','APOLLOHOSP','APOLLOTYRE','ASAHIINDIA','ASHOKLEY','ASHOKA','ASIANPAINT','ASTERDM','ASTRAZEN','ASTRAL','ATUL','AUROPHARMA','AVANTIFEED','DMART','AXISBANK','BASF','BEML','BSE','BAJAJ-AUTO','BAJAJCON','BAJAJELEC','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','BALAMINES','BALKRISIND','BALMLAWRIE','BALRAMCHIN','BANDHANBNK','BANKBARODA','BANKINDIA','MAHABANK','BATAINDIA','BAYERCROP','BERGEPAINT','BDL','BEL','BHARATFORG','BHEL','BPCL','BHARATRAS','BHARTIARTL','BIOCON','BIRLACORPN','BSOFT','BLISSGVS','BLUEDART','BLUESTARCO','BBTC','BOSCHLTD','BRIGADE','BRITANNIA','BURGERKING','CCL','CESC','CRISIL','CSBBANK','CADILAHC','CANFINHOME','CANBK','CAPLIPOINT','CGCL','CARBORUNIV','CASTROLIND','CEATLTD','CENTRALBK','CDSL','CENTURYPLY','CENTURYTEX','CERA','CHALET','CHAMBLFERT','CHOLAHLDNG','CHOLAFIN','CIPLA','CUB','COALINDIA','COCHINSHIP','COFORGE','COLPAL','CAMS','CONCOR','COROMANDEL','CREDITACC','CROMPTON','CUMMINSIND','CYIENT','DCBBANK','DCMSHRIRAM','DLF','DABUR','DALBHARAT','DEEPAKNTR','DELTACORP','DHANI','DHANUKA','DBL','DISHTV','DCAL','DIVISLAB','DIXON','LALPATHLAB','DRREDDY','EIDPARRY','EIHOTEL','EPL','EDELWEISS','EICHERMOT','ELGIEQUIP','EMAMILTD','ENDURANCE','ENGINERSIN','EQUITAS','ERIS','ESCORTS','EXIDEIND','FDC','FEDERALBNK','FINEORG','FINCABLES','FINPIPE','FSL','FORTIS','FCONSUMER','FRETAIL','GAIL','GEPIL','GMMPFAUDLR','GMRINFRA','GALAXYSURF','GRSE','GARFIBRES','GICRE','GILLETTE','GLAXO','GLENMARK','GODFRYPHLP','GODREJAGRO','GODREJCP','GODREJIND','GODREJPROP','GRANULES','GRAPHITE','GRASIM','GESHIP','GREAVESCOT','GRINDWELL','GUJALKALI','GAEL','FLUOROCHEM','GUJGASLTD','GNFC','GPPL','GSFC','GSPL','GULFOILLUB','HEG','HCLTECH','HDFCAMC','HDFCBANK','HDFCLIFE','HFCL','HAPPSTMNDS','HATSUN','HAVELLS','HEIDELBERG','HEMIPROP','HEROMOTOCO','HSCL','HINDALCO','HAL','HINDCOPPER','HINDPETRO','HINDUNILVR','HINDZINC','HONAUT','HUDCO','HDFC','HUHTAMAKI','ICICIBANK','ICICIGI','ICICIPRULI','ISEC','IDBI','IDFCFIRSTB','IDFC','IFBIND','IIFL','IIFLWAM','IOLCP','IRB','IRCON','ITC','ITI','INDIACEM','IBULHSGFIN','IBREALEST','INDIAMART','INDIANB','IEX','INDHOTEL','IOC','IOB','IRCTC','ICIL','INDOCO','IGL','INDUSTOWER','INDUSINDBK','INFIBEAM','NAUKRI','INFY','INGERRAND','INOXLEISUR','INTELLECT','INDIGO','IPCALAB','JBCHEPHARM','JKCEMENT','JKLAKSHMI','JKPAPER','JKTYRE','JMFINANCIL','JSWENERGY','JSWSTEEL','JTEKTINDIA','JAMNAAUTO','JINDALSAW','JSLHISAR','JSL','JINDALSTEL','JCHAC','JUBLFOOD','JUSTDIAL','JYOTHYLAB','KPRMILL','KEI','KNRCON','KPITTECH','KRBL','KSB','KAJARIACER','KALPATPOWR','KANSAINER','KARURVYSYA','KSCL','KEC','KOTAKBANK','L&TFH','LTTS','LICHSGFIN','LAOPALA','LAXMIMACH','LTI','LT','LAURUSLABS','LEMONTREE','LINDEINDIA','LUPIN','LUXIND','MASFIN','MMTC','MOIL','MRF','MGL','MAHSCOOTER','MAHSEAMLES','M&MFIN','M&M','MAHINDCIE','MHRIL','MAHLOG','MANAPPURAM','MRPL','MARICO','MARUTI','MFSL','MAXHEALTH','MAZDOCK','METROPOLIS','MINDTREE','MINDACORP','MINDAIND','MIDHANI','MOTHERSUMI','MOTILALOFS','MPHASIS','MCX','MUTHOOTFIN','NATCOPHARM','NBCC','NCC','NESCO','NHPC','NLCINDIA','NMDC','NOCIL','NTPC','NH','NATIONALUM','NFL','NAVINFLUOR','NESTLEIND','NETWORK18','NILKAMAL','NAM-INDIA','OBEROIRLTY','ONGC','OIL','OFSS','ORIENTELEC','ORIENTREF','PIIND','PNBHOUSING','PNCINFRA','PVR','PAGEIND','PERSISTENT','PETRONET','PFIZER','PHILIPCARB','PHOENIXLTD','PIDILITIND','PEL','POLYMED','POLYCAB','POLYPLEX','PFC','POWERGRID','PRESTIGE','PRINCEPIPE','PRSMJOHNSN','PGHL','PGHH','PNB','QUESS','RBLBANK','RECLTD','RITES','RADICO','RVNL','RAIN','RAJESHEXPO','RALLIS','RCF','RATNAMANI','RAYMOND','REDINGTON','RELAXO','RELIANCE','RESPONIND','ROSSARI','ROUTE','SBICARD','SBILIFE','SIS','SJVN','SKFINDIA','SRF','SANOFI','SCHAEFFLER','SCHNEIDER','SEQUENT','SHARDACROP','SFL','SHILPAMED','SCI','SHOPERSTOP','SHREECEM','SHRIRAMCIT','SRTRANSFIN','SIEMENS','SOBHA','SOLARINDS','SOLARA','SONATSOFTW','SPANDANA','SPICEJET','STARCEMENT','SBIN','SAIL','SWSOLAR','STLTECH','STAR','SUDARSCHEM','SUMICHEM','SPARC','SUNPHARMA','SUNTV','SUNCLAYLTD','SUNDARMFIN','SUNDRMFAST','SUNTECK','SUPRAJIT','SUPREMEIND','SUPPETRO','SUVENPHAR','SUZLON','SWANENERGY','SYMPHONY','SYNGENE','TCIEXP','TCNSBRANDS','TTKPRESTIG','TV18BRDCST','TVSMOTOR','TANLA','TASTYBITE','TATACHEM','TATACOFFEE','TATACOMM','TCS','TATACONSUM','TATAELXSI','TATAINVEST','TATAMTRDVR','TATAMOTORS','TATAPOWER','TATASTEEL','TEAMLEASE','TECHM','NIACL','RAMCOCEM','THERMAX','THYROCARE','TIMKEN','TITAN','TORNTPHARM','TORNTPOWER','TRENT','TRIDENT','TRITURBINE','TIINDIA','UCOBANK','UFLEX','UPL','UTIAMC','UJJIVAN','UJJIVANSFB','ULTRACEMCO','UNIONBANK','UBL','MCDOWELL-N','VGUARD','VMART','VIPIND','VSTIND','VAIBHAVGBL','VAKRANGEE','VALIANTORG','VTL','VARROC','VBL','VEDL','VENKEYS','VINATIORGA','IDEA','VOLTAS','WABCOINDIA','WELCORP','WELSPUNIND','WESTLIFE','WHIRLPOOL','WIPRO','WOCKPHARMA','YESBANK','ZEEL','ZENSARTECH','ZYDUSWELL','ECLERX']
     Optimised_500 = ['NSE:3MINDIA', 'NSE:ABB', 'NSE:POWERINDIA', 'NSE:ACC', 'NSE:AIAENG', 'NSE:APLAPOLLO', 'NSE:AUBANK', 'NSE:AARTIDRUGS', 'NSE:AARTIIND', 'NSE:AAVAS', 'NSE:ABBOTINDIA', 'NSE:ADANIENT', 'NSE:ADANIGREEN', 'NSE:ADANIPORTS', 'NSE:ATGL', 'NSE:ADANITRANS', 'NSE:ABCAPITAL', 'NSE:ABFRL', 'NSE:ADVENZYMES', 'NSE:AEGISCHEM', 'NSE:AFFLE', 'NSE:AJANTPHARM', 'NSE:AKZOINDIA', 'NSE:ALEMBICLTD', 'NSE:APLLTD', 'NSE:ALKEM', 'NSE:ALKYLAMINE', 'NSE:ALOKINDS', 'NSE:AMARAJABAT', 'NSE:AMBER', 'NSE:AMBUJACEM', 'NSE:ANGELBRKG', 'NSE:APOLLOHOSP', 'NSE:APOLLOTYRE', 'NSE:ASAHIINDIA', 'NSE:ASHOKLEY', 'NSE:ASHOKA', 'NSE:ASIANPAINT', 'NSE:ASTERDM', 'NSE:ASTRAZEN', 'NSE:ASTRAL', 'NSE:ATUL', 'NSE:AUROPHARMA', 'NSE:AVANTIFEED', 'NSE:DMART', 'NSE:AXISBANK', 'NSE:BASF', 'NSE:BEML', 'NSE:BSE', 'NSE:BAJAJ-AUTO', 'NSE:BAJAJCON', 'NSE:BAJAJELEC', 'NSE:BAJFINANCE', 'NSE:BAJAJFINSV', 'NSE:BAJAJHLDNG', 'NSE:BALAMINES', 'NSE:BALKRISIND', 'NSE:BALMLAWRIE', 'NSE:BALRAMCHIN', 'NSE:BANDHANBNK', 'NSE:BANKBARODA', 'NSE:BANKINDIA', 'NSE:MAHABANK', 'NSE:BATAINDIA', 'NSE:BAYERCROP', 'NSE:BERGEPAINT', 'NSE:BDL', 'NSE:BEL', 'NSE:BHARATFORG', 'NSE:BHEL', 'NSE:BPCL', 'NSE:BHARATRAS', 'NSE:BHARTIARTL', 'NSE:BIOCON', 'NSE:BIRLACORPN', 'NSE:BSOFT', 'NSE:BLISSGVS', 'NSE:BLUEDART', 'NSE:BLUESTARCO', 'NSE:BBTC', 'NSE:BOSCHLTD', 'NSE:BRIGADE', 'NSE:BRITANNIA', 'NSE:BURGERKING', 'NSE:CCL', 'NSE:CESC', 'NSE:CRISIL', 'NSE:CSBBANK', 'NSE:CADILAHC', 'NSE:CANFINHOME', 'NSE:CANBK', 'NSE:CAPLIPOINT', 'NSE:CGCL', 'NSE:CARBORUNIV', 'NSE:CASTROLIND', 'NSE:CEATLTD', 'NSE:CENTRALBK', 'NSE:CDSL', 'NSE:CENTURYPLY', 'NSE:CENTURYTEX', 'NSE:CERA', 'NSE:CHALET', 'NSE:CHAMBLFERT', 'NSE:CHOLAHLDNG', 'NSE:CHOLAFIN', 'NSE:CIPLA', 'NSE:CUB', 'NSE:COALINDIA', 'NSE:COCHINSHIP', 'NSE:COFORGE', 'NSE:COLPAL', 'NSE:CAMS', 'NSE:CONCOR', 'NSE:COROMANDEL', 'NSE:CREDITACC', 'NSE:CROMPTON', 'NSE:CUMMINSIND', 'NSE:CYIENT', 'NSE:DCBBANK', 'NSE:DCMSHRIRAM', 'NSE:DLF', 'NSE:DABUR', 'NSE:DALBHARAT', 'NSE:DEEPAKNTR', 'NSE:DELTACORP', 'NSE:DHANI', 'NSE:DHANUKA', 'NSE:DBL', 'NSE:DISHTV', 'NSE:DCAL', 'NSE:DIVISLAB', 'NSE:DIXON', 'NSE:LALPATHLAB', 'NSE:DRREDDY', 'NSE:EIDPARRY', 'NSE:EIHOTEL', 'NSE:EPL', 'NSE:EDELWEISS', 'NSE:EICHERMOT', 'NSE:ELGIEQUIP', 'NSE:EMAMILTD', 'NSE:ENDURANCE', 'NSE:ENGINERSIN', 'NSE:EQUITAS', 'NSE:ERIS', 'NSE:ESCORTS', 'NSE:EXIDEIND', 'NSE:FDC', 'NSE:FEDERALBNK', 'NSE:FINEORG', 'NSE:FINCABLES', 'NSE:FINPIPE', 'NSE:FSL', 'NSE:FORTIS', 'NSE:FCONSUMER', 'NSE:FRETAIL', 'NSE:GAIL', 'NSE:GEPIL', 'NSE:GMMPFAUDLR', 'NSE:GMRINFRA', 'NSE:GALAXYSURF', 'NSE:GRSE', 'NSE:GARFIBRES', 'NSE:GICRE', 'NSE:GILLETTE', 'NSE:GLAXO', 'NSE:GLENMARK', 'NSE:GODFRYPHLP', 'NSE:GODREJAGRO', 'NSE:GODREJCP', 'NSE:GODREJIND', 'NSE:GODREJPROP', 'NSE:GRANULES', 'NSE:GRAPHITE', 'NSE:GRASIM', 'NSE:GESHIP', 'NSE:GREAVESCOT', 'NSE:GRINDWELL', 'NSE:GUJALKALI', 'NSE:GAEL', 'NSE:FLUOROCHEM', 'NSE:GUJGASLTD', 'NSE:GNFC', 'NSE:GPPL', 'NSE:GSFC', 'NSE:GSPL', 'NSE:GULFOILLUB', 'NSE:HEG', 'NSE:HCLTECH', 'NSE:HDFCAMC', 'NSE:HDFCBANK', 'NSE:HDFCLIFE', 'NSE:HFCL', 'NSE:HAPPSTMNDS', 'NSE:HATSUN', 'NSE:HAVELLS', 'NSE:HEIDELBERG', 'NSE:HEMIPROP', 'NSE:HEROMOTOCO', 'NSE:HSCL', 'NSE:HINDALCO', 'NSE:HAL', 'NSE:HINDCOPPER', 'NSE:HINDPETRO', 'NSE:HINDUNILVR', 'NSE:HINDZINC', 'NSE:HONAUT', 'NSE:HUDCO', 'NSE:HDFC', 'NSE:HUHTAMAKI', 'NSE:ICICIBANK', 'NSE:ICICIGI', 'NSE:ICICIPRULI', 'NSE:ISEC', 'NSE:IDBI', 'NSE:IDFCFIRSTB', 'NSE:IDFC', 'NSE:IFBIND', 'NSE:IIFL', 'NSE:IIFLWAM', 'NSE:IOLCP', 'NSE:IRB', 'NSE:IRCON', 'NSE:ITC', 'NSE:ITI', 'NSE:INDIACEM', 'NSE:IBULHSGFIN', 'NSE:IBREALEST', 'NSE:INDIAMART', 'NSE:INDIANB', 'NSE:IEX', 'NSE:INDHOTEL', 'NSE:IOC', 'NSE:IOB', 'NSE:IRCTC', 'NSE:ICIL', 'NSE:INDOCO', 'NSE:IGL', 'NSE:INDUSTOWER', 'NSE:INDUSINDBK', 'NSE:INFIBEAM', 'NSE:NAUKRI', 'NSE:INFY', 'NSE:INGERRAND', 'NSE:INOXLEISUR', 'NSE:INTELLECT', 'NSE:INDIGO', 'NSE:IPCALAB', 'NSE:JBCHEPHARM', 'NSE:JKCEMENT', 'NSE:JKLAKSHMI', 'NSE:JKPAPER', 'NSE:JKTYRE', 'NSE:JMFINANCIL', 'NSE:JSWENERGY', 'NSE:JSWSTEEL', 'NSE:JTEKTINDIA', 'NSE:JAMNAAUTO', 'NSE:JINDALSAW', 'NSE:JSLHISAR', 'NSE:JSL', 'NSE:JINDALSTEL', 'NSE:JCHAC', 'NSE:JUBLFOOD', 'NSE:JUSTDIAL', 'NSE:JYOTHYLAB', 'NSE:KPRMILL', 'NSE:KEI', 'NSE:KNRCON', 'NSE:KPITTECH', 'NSE:KRBL', 'NSE:KSB', 'NSE:KAJARIACER', 'NSE:KALPATPOWR', 'NSE:KANSAINER', 'NSE:KARURVYSYA', 'NSE:KSCL', 'NSE:KEC', 'NSE:KOTAKBANK', 'NSE:L&TFH', 'NSE:LTTS', 'NSE:LICHSGFIN', 'NSE:LAOPALA', 'NSE:LAXMIMACH', 'NSE:LTI', 'NSE:LT', 'NSE:LAURUSLABS', 'NSE:LEMONTREE', 'NSE:LINDEINDIA', 'NSE:LUPIN', 'NSE:LUXIND', 'NSE:MASFIN', 'NSE:MMTC', 'NSE:MOIL', 'NSE:MRF', 'NSE:MGL', 'NSE:MAHSCOOTER', 'NSE:MAHSEAMLES', 'NSE:M&MFIN', 'NSE:M&M', 'NSE:MAHINDCIE', 'NSE:MHRIL', 'NSE:MAHLOG', 'NSE:MANAPPURAM', 'NSE:MRPL', 'NSE:MARICO', 'NSE:MARUTI', 'NSE:MFSL', 'NSE:MAXHEALTH', 'NSE:MAZDOCK', 'NSE:METROPOLIS', 'NSE:MINDTREE', 'NSE:MINDACORP', 'NSE:MINDAIND', 'NSE:MIDHANI', 'NSE:MOTHERSUMI', 'NSE:MOTILALOFS', 'NSE:MPHASIS', 'NSE:MCX', 'NSE:MUTHOOTFIN', 'NSE:NATCOPHARM', 'NSE:NBCC', 'NSE:NCC', 'NSE:NESCO', 'NSE:NHPC', 'NSE:NLCINDIA', 'NSE:NMDC', 'NSE:NOCIL', 'NSE:NTPC', 'NSE:NH', 'NSE:NATIONALUM', 'NSE:NFL', 'NSE:NAVINFLUOR', 'NSE:NESTLEIND', 'NSE:NETWORK18', 'NSE:NILKAMAL', 'NSE:NAM-INDIA', 'NSE:OBEROIRLTY', 'NSE:ONGC', 'NSE:OIL', 'NSE:OFSS', 'NSE:ORIENTELEC', 'NSE:ORIENTREF', 'NSE:PIIND', 'NSE:PNBHOUSING', 'NSE:PNCINFRA', 'NSE:PVR', 'NSE:PAGEIND', 'NSE:PERSISTENT', 'NSE:PETRONET', 'NSE:PFIZER', 'NSE:PHILIPCARB', 'NSE:PHOENIXLTD', 'NSE:PIDILITIND', 'NSE:PEL', 'NSE:POLYMED', 'NSE:POLYCAB', 'NSE:POLYPLEX', 'NSE:PFC', 'NSE:POWERGRID', 'NSE:PRESTIGE', 'NSE:PRINCEPIPE', 'NSE:PRSMJOHNSN', 'NSE:PGHL', 'NSE:PGHH', 'NSE:PNB', 'NSE:QUESS', 'NSE:RBLBANK', 'NSE:RECLTD', 'NSE:RITES', 'NSE:RADICO', 'NSE:RVNL', 'NSE:RAIN', 'NSE:RAJESHEXPO', 'NSE:RALLIS', 'NSE:RCF', 'NSE:RATNAMANI', 'NSE:RAYMOND', 'NSE:REDINGTON', 'NSE:RELAXO', 'NSE:RELIANCE', 'NSE:RESPONIND', 'NSE:ROSSARI', 'NSE:ROUTE', 'NSE:SBICARD', 'NSE:SBILIFE', 'NSE:SIS', 'NSE:SJVN', 'NSE:SKFINDIA', 'NSE:SRF', 'NSE:SANOFI', 'NSE:SCHAEFFLER', 'NSE:SCHNEIDER', 'NSE:SEQUENT', 'NSE:SHARDACROP', 'NSE:SFL', 'NSE:SHILPAMED', 'NSE:SCI', 'NSE:SHOPERSTOP', 'NSE:SHREECEM', 'NSE:SHRIRAMCIT', 'NSE:SRTRANSFIN', 'NSE:SIEMENS', 'NSE:SOBHA', 'NSE:SOLARINDS', 'NSE:SOLARA', 'NSE:SONATSOFTW', 'NSE:SPANDANA', 'NSE:SPICEJET', 'NSE:STARCEMENT', 'NSE:SBIN', 'NSE:SAIL', 'NSE:SWSOLAR', 'NSE:STLTECH', 'NSE:STAR', 'NSE:SUDARSCHEM', 'NSE:SUMICHEM', 'NSE:SPARC', 'NSE:SUNPHARMA', 'NSE:SUNTV', 'NSE:SUNCLAYLTD', 'NSE:SUNDARMFIN', 'NSE:SUNDRMFAST', 'NSE:SUNTECK', 'NSE:SUPRAJIT', 'NSE:SUPREMEIND', 'NSE:SUPPETRO', 'NSE:SUVENPHAR', 'NSE:SUZLON', 'NSE:SWANENERGY', 'NSE:SYMPHONY', 'NSE:SYNGENE', 'NSE:TCIEXP', 'NSE:TCNSBRANDS', 'NSE:TTKPRESTIG', 'NSE:TV18BRDCST', 'NSE:TVSMOTOR', 'NSE:TANLA', 'NSE:TASTYBITE', 'NSE:TATACHEM', 'NSE:TATACOFFEE', 'NSE:TATACOMM', 'NSE:TCS', 'NSE:TATACONSUM', 'NSE:TATAELXSI', 'NSE:TATAINVEST', 'NSE:TATAMTRDVR', 'NSE:TATAMOTORS', 'NSE:TATAPOWER', 'NSE:TATASTEEL', 'NSE:TEAMLEASE', 'NSE:TECHM', 'NSE:NIACL', 'NSE:RAMCOCEM', 'NSE:THERMAX', 'NSE:THYROCARE', 'NSE:TIMKEN', 'NSE:TITAN', 'NSE:TORNTPHARM', 'NSE:TORNTPOWER', 'NSE:TRENT', 'NSE:TRIDENT', 'NSE:TRITURBINE', 'NSE:TIINDIA', 'NSE:UCOBANK', 'NSE:UFLEX', 'NSE:UPL', 'NSE:UTIAMC', 'NSE:UJJIVAN', 'NSE:UJJIVANSFB', 'NSE:ULTRACEMCO', 'NSE:UNIONBANK', 'NSE:UBL', 'NSE:MCDOWELL-N', 'NSE:VGUARD', 'NSE:VMART', 'NSE:VIPIND', 'NSE:VSTIND', 'NSE:VAIBHAVGBL', 'NSE:VAKRANGEE', 'NSE:VALIANTORG', 'NSE:VTL', 'NSE:VARROC', 'NSE:VBL', 'NSE:VEDL', 'NSE:VENKEYS', 'NSE:VINATIORGA', 'NSE:IDEA', 'NSE:VOLTAS', 'NSE:WABCOINDIA', 'NSE:WELCORP', 'NSE:WELSPUNIND', 'NSE:WESTLIFE', 'NSE:WHIRLPOOL', 'NSE:WIPRO', 'NSE:WOCKPHARMA', 'NSE:YESBANK', 'NSE:ZEEL', 'NSE:ZENSARTECH', 'NSE:ZYDUSWELL', 'NSE:ECLERX']

2.   ob = margins['equity']['available']['opening_balance']
	 realised_m2m  = margins['equity']['utilised']['m2m_realised']	

3.   Login to zerodha

import zrd_login
kite = zrd_login.kite
from pprint import pprint

4. ltp = kite.ltp(['NSE:' + name])['NSE:' + name]['last_price']
5. openn = kite.ohlc(['NSE:' + name])['NSE:' + name]['ohlc']['openn']
8. high = kite.ohlc(['NSE:' + name])['NSE:' + name]['ohlc']['high']
7. low = kite.ohlc(['NSE:' + name])['NSE:' + name]['ohlc']['low']
8. close = kite.ohlc(['NSE:' + name])['NSE:' + name]['ohlc']['close']
9. bid_price = kite.quote(['NSE:'+ name])['NSE:'+ name]['depth']['buy'][0]['price']
10.Ask_price = kite.quote(['NSE:'+ name])['NSE:'+ name]['depth']['sell'][0]['price']
11.spread = round(Ask_price - bid_price,2)
12.volume = kite.quote(['NSE:'+ name])['NSE:'+ name]['volume']

13.
	book_profit = 0.001
	limit_sell = 3052
	limit_buy = round(limit_sell-book_pro*limit_sell,1)


Step_value = {'AARTIIND':20,'ACC':20,'ADANIENT':10,'ADANIPORTS':10,'AMARAJABAT':10,'AMBUJACEM':5,'APOLLOHOSP':50,'APOLLOTYRE':2.5,'ASHOKLEY':2.5,'ASIANPAINT':20,'AUROPHARMA':10,'AXISBANK':10,'BAJAJ-AUTO':50,'BAJAJFINSV':100,'BAJFINANCE':100,'BALKRISIND':20,'BANDHANBNK':10,'BANKBARODA':1,'BATAINDIA':20,'BEL':2.5,'BERGEPAINT':10,'BHARATFORG':10,'BHARTIARTL':10,'BHEL':1,'BIOCON':5,'BOSCHLTD':250,'BPCL':5,'BRITANNIA':50,'CADILAHC':5,'CANBK':2.5,'CHOLAFIN':10,'CIPLA':10,'COALINDIA':2.5,'COFORGE':50,'COLPAL':20,'CONCOR':5,'CUMMINSIND':10,'DABUR':5,'DIVISLAB':50,'DLF':5,'DRREDDY':50,'EICHERMOT':50,'ESCORTS':20,'EXIDEIND':2.5,'FEDERALBNK':1,'GAIL':2.5,'GLENMARK':10,'GMRINFRA':1,'GODREJCP':10,'GODREJPROP':20,'GRASIM':10,'HAVELLS':10,'HCLTECH':10,'HDFC':20,'HDFCAMC':20,'HDFCBANK':20,'HDFCLIFE':10,'HEROMOTOCO':50,'HINDALCO':5,'HINDPETRO':5,'HINDUNILVR':20,'IBULHSGFIN':5,'ICICIBANK':10,'ICICIGI':20,'ICICIPRULI':10,'IDEA':1,'IDFCFIRSTB':1,'IGL':5,'INDIGO':20,'INDUSINDBK':20,'INFRATEL':5,'INFY':20,'IOC':1,'ITC':2.5,'JINDALSTEL':5,'JSWSTEEL':5,'JUBLFOOD':50,'KOTAKBANK':20,'L&TFH':2.5,'LALPATHLAB':50,'LICHSGFIN':10,'LT':20,'LUPIN':10,'M&M':10,'M&MFIN':5,'MANAPPURAM':2.5,'MARICO':5,'MARUTI':100,'MCDOWELL-N':10,'MFSL':10,'MGL':20,'MINDTREE':20,'MOTHERSUMI':2.5,'MRF':500,'MUTHOOTFIN':20,'NATIONALUM':1,'NAUKRI':100,'NESTLEIND':100,'NMDC':2.5,'NTPC':1,'ONGC':1,'PAGEIND':500,'PEL':20,'PETRONET':5,'PFC':2.5,'PIDILITIND':20,'PNB':1,'POWERGRID':2.5,'PVR':20,'RAMCOCEM':10,'RBLBANK':5,'RECLTD':2.5,'RELIANCE':20,'SAIL':1,'SBILIFE':10,'SBIN':5,'SHREECEM':250,'SIEMENS':20,'SRF':50,'SRTRANSFIN':20,'SUNPHARMA':10,'SUNTV':10,'TATACHEM':10,'TATACONSUM':10,'TATAMOTORS':5,'TATAPOWER':1,'TATASTEEL':10,'TCS':20,'TECHM':10,'TITAN':20,'TORNTPHARM':50,'TORNTPOWER':5,'TVSMOTOR':10,'UBL':20,'ULTRACEMCO':50,'UPL':10,'VEDL':2.5,'VOLTAS':10,'WIPRO':5,'ZEEL':5,}
Index_dict = {258313:'CPSE INDEX',264713:'HANGSENG BEES-NAV',264969:'INDIA VIX',258057:'LIX 15',258569:'NI15',260617:'NIFTY 100',264457:'NIFTY 200',256265:'NIFTY 50',268041:'NIFTY 500',265993:'NIFTY ALPHA 50',273673:'NIFTY ALPHALOWVOL',263433:'NIFTY AUTO',260105:'NIFTY BANK',257289:'NIFTY COMMODITIES',257545:'NIFTY CONSUMPTION',268297:'NIFTY CPSE',257033:'NIFTY DIV OPPS 50',261641:'NIFTY ENERGY',257801:'NIFTY FIN SERVICE',261897:'NIFTY FMCG',270345:'NIFTY GROWSECT 15',269065:'NIFTY GS 10YR',269321:'NIFTY GS 10YR CLN',269577:'NIFTY GS 11 15YR',269833:'NIFTY GS 15YRPLUS',268553:'NIFTY GS 4 8YR',268809:'NIFTY GS 8 13YR',270089:'NIFTY GS COMPSITE',261385:'NIFTY INFRA',259849:'NIFTY IT',263945:'NIFTY MEDIA',263689:'NIFTY METAL',270601:'NIFTY MID LIQ 15',256777:'NIFTY MIDCAP 100',266249:'NIFTY MIDCAP 150',260873:'NIFTY MIDCAP 50',266505:'NIFTY MIDSML 400',262153:'NIFTY MNC',270857:'NIFTY NEXT 50',262409:'NIFTY PHARMA',262665:'NIFTY PSE',262921:'NIFTY PSU BANK',271113:'NIFTY PVT BANK',261129:'NIFTY REALTY',263177:'NIFTY SERV SECTOR',267017:'NIFTY SMLCAP 100',267273:'NIFTY SMLCAP 250',266761:'NIFTY SMLCAP 50',271881:'NIFTY100 EQL WGT',267785:'NIFTY100 LIQ 15',272137:'NIFTY100 LOWVOL30',272393:'NIFTY100 QUALTY30',265737:'NIFTY200 QUALTY30',265225:'NIFTY50 DIV POINT',271625:'NIFTY50 EQL WGT',259081:'NIFTY50 PR 1X INV',258825:'NIFTY50 PR 2X LEV',259593:'NIFTY50 TR 1X INV',259337:'NIFTY50 TR 2X LEV',267529:'NIFTY50 VALUE 20'}
step_value = {'AARTIIND':20,'ACC':20,'ADANIENT':20,'ADANIPORTS':10,'ALKEM':20,'AMARAJABAT':10,'AMBUJACEM':5,'APLLTD':10,'APOLLOHOSP':50,'APOLLOTYRE':5,'ASHOKLEY':2.5,'ASIANPAINT':20,'AUBANK':20,'AUROPHARMA':10,'AXISBANK':10,'BAJAJ-AUTO':50,'BAJAJFINSV':100,'BAJFINANCE':100,'BALKRISIND':20,'BANDHANBNK':5,'BANKBARODA':2.5,'BATAINDIA':20,'BEL':2.5,'BERGEPAINT':10,'BHARATFORG':10,'BHARTIARTL':10,'BHEL':1,'BIOCON':5,'BOSCHLTD':250,'BPCL':10,'BRITANNIA':20,'CADILAHC':5,'CANBK':5,'CHOLAFIN':10,'CIPLA':10,'COALINDIA':2.5,'COFORGE':50,'COLPAL':20,'CONCOR':10,'CUB':2.5,'CUMMINSIND':20,'DABUR':5,'DEEPAKNTR':20,'DIVISLAB':50,'DLF':5,'DRREDDY':50,'EICHERMOT':50,'ESCORTS':20,'EXIDEIND':2.5,'FEDERALBNK':1,'GAIL':2.5,'GLENMARK':5,'GMRINFRA':1,'GODREJCP':10,'GODREJPROP':20,'GRANULES':5,'GRASIM':20,'GUJGASLTD':10,'HAVELLS':20,'HCLTECH':10,'HDFC':50,'HDFCAMC':50,'HDFCBANK':20,'HDFCLIFE':10,'HEROMOTOCO':50,'HINDALCO':5,'HINDPETRO':5,'HINDUNILVR':20,'IBULHSGFIN':5,'ICICIBANK':10,'ICICIGI':20,'ICICIPRULI':5,'IDEA':1,'IDFCFIRSTB':1,'IGL':10,'INDIGO':20,'INDUSINDBK':20,'INDUSTOWER':5,'INFY':20,'IOC':1,'IRCTC':20,'ITC':2.5,'JINDALSTEL':10,'JSWSTEEL':10,'JUBLFOOD':50,'KOTAKBANK':20,'L&TFH':2.5,'LALPATHLAB':50,'LICHSGFIN':10,'LT':20,'LTI':100,'LTTS':50,'LUPIN':20,'M&M':10,'M&MFIN':5,'MANAPPURAM':2.5,'MARICO':5,'MARUTI':100,'MCDOWELL-N':5,'MFSL':20,'MGL':20,'MINDTREE':20,'MOTHERSUMI':5,'MPHASIS':20,'MRF':500,'MUTHOOTFIN':20,'NAM-INDIA':5,'NATIONALUM':1,'NAUKRI':100,'NAVINFLUOR':50,'NESTLEIND':100,'NMDC':2.5,'NTPC':1,'ONGC':2.5,'PAGEIND':500,'PEL':50,'PETRONET':5,'PFC':2.5,'PFIZER':50,'PIDILITIND':20,'PIIND':20,'PNB':1,'POWERGRID':2.5,'PVR':20,'RAMCOCEM':10,'RBLBANK':5,'RECLTD':2.5,'RELIANCE':20,'SAIL':5,'SBILIFE':10,'SBIN':5,'SHREECEM':500,'SIEMENS':20,'SRF':100,'SRTRANSFIN':20,'SUNPHARMA':10,'SUNTV':10,'TATACHEM':10,'TATACONSUM':10,'TATAMOTORS':5,'TATAPOWER':2.5,'TATASTEEL':20,'TCS':50,'TECHM':20,'TITAN':20,'TORNTPHARM':20,'TORNTPOWER':5,'TRENT':20,'TVSMOTOR':10,'UBL':20,'ULTRACEMCO':100,'UPL':10,'VEDL':5,'VOLTAS':20,'WIPRO':5,'ZEEL':5,}

# Create xl_book
wb = xw.Book()
filename = str(datetime.datetime.now().date()) + 'tradebook' + '.xlsx'
wb.save(filename)

name = xw.Book(filename)

sht = name.sheets['Sheet1']

sht.range('A1').value = 'Stock Name'
sht.range('A2').value = 55889999
wb.save(filename)

# ATM Strike Formula
atm_strike = round(ltp/step_value)*step_value
		name+str(strike)+'21MAY'+CE


# Cancel all Order in one command
orderbook = kite.orders()

for order in orderbook:
	try:
		kite.cancel_order(variety=kite.VARIETY_AMO, order_id = order['order_id'],parent_order_id=None)
	except Exception as e:
		print(e,order['order_id'])
		pass
		



# Cancel order form order_history
var = kite.order_history(order_id=order_id_tp)

#datetime all things

start_after = datetime.time(9, 16)

print(datetime.datetime.now()) # = 2021-05-23 22:02:15.495334
print(datetime.datetime.now().microsecond) # 501308
print(datetime.datetime.now().time()) # 22:02:19.507663
print(datetime.datetime.now().date()) # 2021-05-23
print(datetime.datetime.now().day) #  23
print(datetime.datetime.now().month) # 5
print(datetime.datetime.now().year) # 2021
print(datetime.datetime.now().second) # 29
print(datetime.datetime.now().minute) # 2
print(datetime.datetime.now().hour) # 22
print(datetime.datetime.now().weekday())  #
# Month first 3 letters in upper case 
month = getDate.strftime("%Y-%B-%d").upper()[5:8]
or
month_first_3_letters_upper_case = print(datetime.datetime.now().strftime("%b").upper())
year_last_two_digit = print(datetime.datetime.now().strftime("%y"))



## while break statement

while True:
    for x in range(5):
        if (x==4):
            print('Yes')
            break
    break


import winsound

winsound.Beep(frequency=750, duration=100) # Excecution Sound
	
winsound.Beep(frequency=750, duration=1000) # Stop loss Sound


# Download and save data !

name = name
df = sf.get_data(name = name, segment = 'NSE:', delta = 1, interval= 'minute', continuous= False, oi=False)
df.to_csv('Folder_name' + '\\' +name + '.csv')
print(name)


common status
status = 

{

'name':None
'date':None
'buy_script':None
'sell_script':None
'buy_ltp':None
'sell_ltp':None
'entry_time':None
'qty':None
'sl':None
'target':None
'exit_time':None
'pnl':None
'remark':None
'tarded':None
'remark2':None

}

status = {'name':None, 'date':None, 'buy_script':None, 'sell_script':None, 'buy_ltp':None, 'sell_ltp':None, 'entry_time':None, 'qty':None, 'sl':None, 'target':None, 'exit_time':None, 'pnl':None, 'remark':None, 'tarded':None, 'remark2':None}

# Instrument File

inst = pd.read_csv('inst.csv')
inst = inst.set_index(inst['tradingsymbol'])
pdb.set_trace()


# Completed Candle

completed_candle = pd.Series(datetime.datetime.now()).dt.floor('15min')[0]- datetime.timedelta(minutes=15)
completed_candle = completed_candle.strftime("%Y-%m-%d %H:%M:%S+05:30")



Standard Status :

status = {'Name':None, 'Entry_Date':None, 'Buy_script':None, 'Sell_script':None, 'Buy_Price':None, 'Sell_Price':None, 'Entry_time':None, 'Qty':None, 'StopLoss':None, 'Target': None, 'Exit_time':None, 'PNL':None, 'Remark':None, 'Traded':None, 'Remark_2':None,'Remark_3':None, 'RSI_value_Buy': None,'RSI_value_Sell': None, 'Exit_Date' : None , 'Exit_time': None}


Pandas code 

# Set Index
df = df.set_index(df['date'])

# Shift 1 index 
df['df_previous_close'] = df['close'].shift(1)


# Oders 
 	mis order
	# mis market
	kite.place_order(variety = kite.VARIETY_REGULAR , exchange = kite.EXCHANGE_NSE , tradingsymbol = name[4:] , transaction_type = kite.TRANSACTION_TYPE_SELL , quantity = 1 , product = kite.PRODUCT_MIS , order_type = kite.ORDER_TYPE_MARKET , price=None, validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	# mis slm
	buy_order_id = kite.place_order(variety=kite.VARIETY_REGULAR, exchange=kite.EXCHANGE_NSE, tradingsymbol=name, transaction_type=kite.TRANSACTION_TYPE_BUY, quantity=qty, product=kite.PRODUCT_MIS, order_type=kite.ORDER_TYPE_SLM, price=None, validity=None, disclosed_quantity=None, trigger_price=buy_trigger_price, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	 amo orders
	kite.place_order(variety = kite.VARIETY_AMO, exchange= kite.EXCHANGE_NSE, tradingsymbol = name, transaction_type = kite.TRANSACTION_TYPE_SELL, quantity = lot_size, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_MARKET, price = None, validity = None, disclosed_quantity = None, trigger_price = None, squareoff = None, stoploss = None, trailing_stoploss = None, tag = None)

	amo market order
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = 'ACC', transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = 36, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_MARKET, price=None, validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	amo slm order
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = 'CIPLA', transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = 360, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_SLM, price=None, validity=None, disclosed_quantity=None, trigger_price=800, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)


	amo limit
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = name , transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = status[name]['qty'] , product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_LIMIT, price=candle['low'], validity=None, disclosed_quantity=None, trigger_price=800, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)



Split Exchange Name 

nifty_50 = ['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BPCL', 'BHARTIARTL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'HDFC', 'ICICIBANK', 'ITC', 'IOC', 'INDUSINDBK', 'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC', 'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SHREECEM', 'SBIN', 'SUNPHARMA', 'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'UPL', 'ULTRACEMCO', 'WIPRO']
watchlist = []
rows=[]

for name in nifty_50:
	watchlist.append('NSE:' + name)

data=kite.ohlc(watchlist)

for name in data:	
	pdb.set_trace()
 	
	dic={} 	
	dic['Name']=name.split(':')[1] 	
	dic['open']=data[name]['ohlc']['open'] 	
	dic['high']=data[name]['ohlc']['high'] 	
	dic['low']=data[name]['ohlc']['low'] 	
	dic['close']=data[name]['ohlc']['close'] 	
	rows.append(dic) 	
	df=pd.DataFrame(rows)


# Date : 20-06-2022 ------------------ Newly Started again----------------------------------------



# Kite Import modules

margins = kite.margins()

holdings = kite.holdings()

posiotions = kite.positions()

orders = kite.orders()

# Time in market start and end algo 

start_time = datetime.time(15 , 11)



while True :
	current_time = datetime.datetime.now().time()

	if current_time > start_time:
		break
	else:
		print(f"Algo is running")


# Option Greek


import mibian
from scipy.stats import norm


underlying_price = 8572
call_strike = 8700
put_strike = 8500
call_price = 616.05
put_price = 654.05
interest_rate = 0
days_to_expiry = 31


# c = mibian.BS([8572, 8700, 0, 31], callPrice= 616.05)
# print(c.impliedVolatility)

ce = mibian.BS([8572, 8700, 0, 31], callPrice = 616.05)
data  = (ce.impliedVolatility)
print(data)

pdb.set_trace()



# BankNifty Option Scalping Algo

step_value = 100
name = 'NIFTY BANK'
ltp = get.LTP(name)
expiry = get.expiry()

atm_strike = round(ltp/step_value)*step_value
data = 'BANKNIFTY'+expiry+str(atm_strike)+'CE'
pdb.set_trace()


status['Name'] =
status['ctime'] =
status['Sell_price'] =
status['Entry_time'] =
status['Target'] =
status['Stoploss'] =
status['Remark'] =


# Xlwings --Excle data 

import xlwings as xw


wb = xw.Book('atul.xlsx')

sht = wb.sheets['Sheet1']

sht.range('B1').value = df

for x in range(100000):

	x = x+1
	x = int(x)
	sht.range('A1').value = x
	time.sleep(1)



# Excel File 

if not os.path.exists("tick_data.xlsx"):
    try:
        wb = xw.Book()
        wb.save('tick_data.xlsx')
        wb.close()
    except Exception as e:
        print(f"Error : {e}")
        sys.exit()
wb = xw.Book('tick_data.xlsx')

sht = wb.sheets['sheet1']

watchlist = 'NIFTY BANK'


df = df.set_index(df['date'])



# leading number with zerodha
number = 1
print("%02d" % (number,))


# ----------Imran-Data-------------------


1. convert string to datetime python
	from dateutil.parser import parse
	datetime = parse('2018-06-29 22:21:41')

	ff = parse('2022-08-02') # Date to day name
	print(ff.strftime("%A"))

2. For loop on pandas
	for index, row in df.iterrows():

3. pandas set index
	df.set_index('month')

3.1 Clear Pandas DataFrame 
	df.drop(df.index,inplace=True) # Clear all Pandas DataFrame

4. pandas rename columns
	df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")

5. pandas select only few columns
	dfx = df[['open', 'high']]

6. replace text in pandas
dfx['date'].str.replace('.', ':')


7. xlwings

import xlwings as xw
wb = xw.Book('results.xlsx')
sht = wb.sheets['Sheet1']
watch_list = sht2.range('A1').expand().value
print(watch_list)

8. 
    dbfile = open('examplePickle', 'ab') 
    pickle.dump(db, dbfile) 

    dbfile = open('examplePickle', 'rb')
    db = pickle.load(dbfile) 

9. slice pnadas string in columns
nifty_dates = df["date"].str.slice(0, 10).unique()


10. python separate numbers from string
int(''.join(filter(str.isdigit, cell_no)))


11. pandas shift column down
	df.['date'].shift(1)

12. pandas put 0 ,1 in place of true false
	df["somecolumn"] = df["somecolumn"].astype(int)


13. datetime combination for example
	dd-mm-yyyy h.mm

14. pandas drop columns
	df = df.drop(['confluence_candle_param'], axis = 1)

15. read data from relatine path
	pd.read_csv("Data Files/nifty.csv")


16. check for instance 
	if isinstance(trailing_indicator, dict):
		pass

17. STEP VALUE
	https://www1.nseindia.com/content/fo/sos_scheme.xls

18. drop columns
	df.drop(['B', 'C'], axis=1)

19. pandas arrange rows by list
	df.reindex(watchlist)
	

20. mis order
	kite.place_order(variety = kite.VARIETY_REGULAR , exchange = kite.EXCHANGE_NSE , tradingsymbol = name[4:] , transaction_type = kite.TRANSACTION_TYPE_SELL , quantity = 1 , product = kite.PRODUCT_MIS , order_type = kite.ORDER_TYPE_MARKET , price=None, validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)


21. amo orders
	kite.place_order(variety = kite.VARIETY_AMO, exchange= kite.EXCHANGE_NSE, tradingsymbol = name, transaction_type = kite.TRANSACTION_TYPE_SELL, quantity = lot_size, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_MARKET, price = None, validity = None, disclosed_quantity = None, trigger_price = None, squareoff = None, stoploss = None, trailing_stoploss = None, tag = None)

	amo market order
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = 'ACC', transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = 36, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_MARKET, price=None, validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	amo slm order
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = 'CIPLA', transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = 360, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_SLM, price=None, validity=None, disclosed_quantity=None, trigger_price=800, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)


22. remove timezone form timestamp
	df['date'] =  df['date'].dt.tz_localize(None)

23.
	from colorama import init
	from colorama import Fore, Back, Style

	init()
	print(Fore.RED + 'some red text')
	Fore: BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, RESET.

24.
	from dateutil.parser import parse
	datetime = parse('2018-06-29 22:21:41')

25. remove timezone
	df.iloc[-1]['date'].replace(tzinfo=None)


26.
	detailed traceback

import traceback
import sys

try:
	print(1/0)
except Exception as e:
	print(e)
	exc_info = sys.exc_info()
	traceback.print_exception(*exc_info)


27. find forst occurance
	candles[candles['rsi'] > 60].first_valid_index()

nifty names storage

nifty100LowVolatility30list : 	['ACC', 'ASIANPAINT', 'BAJAJ-AUTO', 'BOSCHLTD', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'COLPAL', 'DABUR', 'DRREDDY', 'HCLTECH', 'HDFCBANK', 'HEROMOTOCO', 'HINDUNILVR', 'HDFC', 'ITC', 'IOC', 'INFY', 'KOTAKBANK', 'LT', 'MARICO', 'NTPC', 'NESTLEIND', 'PIDILITIND', 'POWERGRID', 'RELIANCE', 'TCS', 'TECHM', 'ULTRACEMCO', 'WIPRO']
nifty200Momentum30_list : 		['ASIANPAINT', 'AUROPHARMA', 'BALKRISIND', 'BERGEPAINT', 'BHARTIARTL', 'BIOCON', 'BRITANNIA', 'CADILAHC', 'CIPLA', 'COLPAL', 'DABUR', 'DIVISLAB', 'DRREDDY', 'ESCORTS', 'GMRINFRA', 'HINDUNILVR', 'IGL', 'NAUKRI', 'JUBLFOOD', 'LUPIN', 'MGL', 'MUTHOOTFIN', 'NESTLEIND', 'PIDILITIND', 'RELIANCE', 'SRF', 'SHREECEM', 'TATACONSUM', 'TORNTPHARM', 'TORNTPOWER']
nifty50list : 					['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BPCL', 'BHARTIARTL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'HDFC', 'ICICIBANK', 'ITC', 'IOC', 'INDUSINDBK', 'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC', 'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SHREECEM', 'SBIN', 'SUNPHARMA', 'TCS', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'UPL', 'ULTRACEMCO', 'WIPRO']
niftymidcap50list : 			['ADANIENT', 'AMARAJABAT', 'APOLLOHOSP', 'APOLLOTYRE', 'ASHOKLEY', 'BALKRISIND', 'BANKINDIA', 'BATAINDIA', 'BEL', 'BHARATFORG', 'BHEL', 'CANBK', 'CASTROLIND', 'CHOLAFIN', 'COFORGE', 'CUMMINSIND', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'GMRINFRA', 'GLENMARK', 'GODREJPROP', 'IDFCFIRSTB', 'IBULHSGFIN', 'JINDALSTEL', 'JUBLFOOD', 'L&TFH', 'LICHSGFIN', 'MRF', 'MGL', 'M&MFIN', 'MANAPPURAM', 'MFSL', 'MINDTREE', 'NATIONALUM', 'PAGEIND', 'RBLBANK', 'RECLTD', 'SRF', 'SRTRANSFIN', 'SAIL', 'SUNTV', 'TVSMOTOR', 'TATAPOWER', 'RAMCOCEM', 'TORNTPOWER', 'UNIONBANK', 'IDEA', 'VOLTAS', 'ZEEL']
niftysmallcap50list : 			['AVANTIFEED', 'BAJAJELEC', 'BDL', 'BIRLACORPN', 'CANFINHOME', 'CEATLTD', 'CENTURYTEX', 'CHAMBLFERT', 'COCHINSHIP', 'CYIENT', 'DCBBANK', 'DCMSHRIRAM', 'DEEPAKNTR', 'DBL', 'DIXON', 'GMMPFAUDLR', 'GODFRYPHLP', 'GRANULES', 'GRAPHITE', 'IDFC', 'IRCON', 'INDIAMART', 'INDIANB', 'KAJARIACER', 'KEC', 'LAURUSLABS', 'LINDEINDIA', 'MOIL', 'MIDHANI', 'MCX', 'NBCC', 'PNBHOUSING', 'PVR', 'PERSISTENT', 'PGHL', 'RITES', 'RADICO', 'RVNL', 'RALLIS', 'SPICEJET', 'STLTECH', 'STAR', 'SPARC', 'SUNTECK', 'TV18BRDCST', 'TATAELXSI', 'UJJIVANSFB', 'VIPIND', 'VAKRANGEE', 'WOCKPHARMA']
nifty_Alpha_Index : 			['ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ATGL', 'AJANTPHARM', 'APLLTD', 'AMBER', 'ASTRAZEN', 'DMART', 'BALKRISIND', 'BAYERCROP', 'BERGEPAINT', 'BSOFT', 'CDSL', 'COFORGE', 'COROMANDEL', 'DEEPAKNTR', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'ESCORTS', 'GMMPFAUDLR', 'GRANULES', 'GUJGASLTD', 'HCLTECH', 'ISEC', 'INDIAMART', 'NAUKRI', 'IPCALAB', 'JBCHEPHARM', 'JINDALSTEL', 'JUBLFOOD', 'LAURUSLABS', 'METROPOLIS', 'MCX', 'MUTHOOTFIN', 'NAVINFLUOR', 'NESTLEIND', 'PIIND', 'RALLIS', 'RELAXO', 'RELIANCE', 'SRF', 'TATACONSUM', 'TORNTPHARM', 'TRENT', 'VBL', 'IDEA']
nifty_alpha_lowvol30list : 		['AMBUJACEM', 'ASIANPAINT', 'BERGEPAINT', 'BIOCON', 'BRITANNIA', 'CADILAHC', 'CIPLA', 'COLPAL', 'DABUR', 'DIVISLAB', 'DRREDDY', 'HCLTECH', 'HAVELLS', 'HINDUNILVR', 'IGL', 'INFY', 'LUPIN', 'MRF', 'MARICO', 'NESTLEIND', 'PIDILITIND', 'POWERGRID', 'RELIANCE', 'SRF', 'SHREECEM', 'TCS', 'TORNTPHARM', 'TORNTPOWER', 'VOLTAS', 'WIPRO']
nifty_High_Beta50_Index : 		['ADANIPORTS', 'APOLLOTYRE', 'ASHOKLEY', 'AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'BANDHANBNK', 'BANKBARODA', 'BHEL', 'BPCL', 'CANFINHOME', 'CANBK', 'CHOLAFIN', 'COFORGE', 'DLF', 'ESCORTS', 'FEDERALBNK', 'GODREJPROP', 'GRASIM', 'HINDALCO', 'HDFC', 'ICICIBANK', 'ICICIPRULI', 'IDFCFIRSTB', 'IBULHSGFIN', 'INDUSINDBK', 'JSWSTEEL', 'JINDALSTEL', 'L&TFH', 'LICHSGFIN', 'M&MFIN', 'MANAPPURAM', 'MARUTI', 'MFSL', 'MOTHERSUMI', 'MUTHOOTFIN', 'NMDC', 'NAM-INDIA', 'PEL', 'PFC', 'RBLBANK', 'RADICO', 'SRTRANSFIN', 'SBIN', 'SAIL', 'TATAMOTORS', 'TATASTEEL', 'UJJIVAN', 'VEDL', 'IDEA']




# os Module change dir


os.getcwd() # get current directory
os.chdir(r'F:/code_atul/Back_Test_data')
os.getcwd() 




Temp and copy status 

watchlist = NIFTY50_List = ['ADANIPORTS', 'ASIANPAINT', 'AXISBANK ', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BPCL', 'BHARTIARTL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'HDFC', 'ICICIBANK', 'ITC', 'IOC', 'INDUSINDBK', 'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC', 'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SHREECEM', 'SBIN', 'SUNPHARMA', 'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'UPL', 'ULTRACEMCO', 'WIPRO']
temp = {'name':None, 'date':None, 'buy_script':None, 'sell_script':None, 'buy_ltp':None, 'sell_ltp':None, 'entry_time':None, 'qty':None, 'sl':None, 'target':None, 'exit_time':None, 'pnl':None, 'remark':None, 'tarded':None, 'remark2':None}
status = {}

for name in watchlist:
	status[name] = temp.copy()

df = pd.DataFrame(status).T 
df.to_excel('Status.xlsx')



Data Download Index

name  = 'NIFTY BANK'
df = get.get_equity_data(name=name, segment='NSE:', delta=60, interval='minute', continuous=False, oi=False)
df = df.to_csv('BankNifty1mintedata.csv')

name  = 'NIFTY 50'
df = get.get_equity_data(name=name, segment='NSE:', delta=60, interval='minute', continuous=False, oi=False)
df = df.to_csv('Nifty1mintedata.csv')

# Calendar Module in python

import calendar
print(calendar.calendar(2022))




read_file and search files 


input_file  = (r"F:\code_atul\Code_back\file")
os.chdir(input_file)

files_list  = os.listdir(input_file)
original_file = files_list[0]

df = pd.read_csv(original_file)

pdb.set_trace()